var emails = [
   "grofis.togma@gmail.com",
   "dawigo.pimaya@gmail.com",
   "dawigo.pimaya@gmail.com"
   ,"pilftos4925@gmail.com",
   "vf59264117@gmail.com"
   ,"high.wiars1051@gmail.com",
   ,"pundofis.asrk@gmail.com",
   "dang.wiht101@gmail.com",
   "uyarsihis.ansla@gmail.com",    
   "opel23686@gmail.com",
   "zee230089@gmail.com",
   "azpremiumax.mail@gmail.com",
   "gameking99@gmail.com",
   "alia1battle21@gmail.com",
   "allisonangel34@gmail.com",
   "amberjack67@gmail.com",
   "kratos241@gmail.com",
    "annastefen9@gmail.com",
    "badbunny911@gmail.com",
    "bazookaman2@gmail.com",
    "bestblade4@gmail.com",
    "captainp3roxide@gmail.com",
    "chasmface65@gmail.com",
    "commando2022@gmail.com",
    "crazyeights4@gmail.com",
    "darksideorbit1@gmail.com",
    "brooke342@gmail.com",
    "freeuse14@gmail.com",
    "freeforyou14@gmail.com",
    "takaagmail@gmail.com",
    "gmailfor25@gmail.com",
    "wantagmail12@gmail.com",
    "gmailolla14@gmail.com",
    "gmaill236@gmail.com",
    "gmail985@gmail.com",
    "gmailpopi36@gmail.com",
    "gmailgenerator85@gmail.com",
    "gmailallday78@gmail.com",
    "freemailadress96@gmail.com",
    "freeusemail87@gmail.com",
    "9654gmail@gmail.com",
    "pokemon4ever72@gmail.com",
    "Caraqu@gmail.com",
    "bahogbelat@gmail.com",
    "updateios27@gmail.com",
    "cmonster@gmail.com",
    "ZartBoyIsBack@gmail.com",
    "arafatexe17@gmail.com",
    "fiazahmada124578@gmail.cm",
    "iosupdate7@gmail.com",
    "ganksterkingx1@gmail.com",
    "ebrarx50452@gmail.com",
    "alicangs205420@gmail.com",
    "fha_melegim@gmail.com",
    "ulfettosun49@gmail.com",
    "krksirm1331@gmail.com",
    "x.kemal54@gmail.com",
    "hsan.fidan200@gmail.com",
    "boxzedit77@gmail.com",
    "yusuf_koroglu1238@gmail.com",
    "axundova010@gmail.com",
    "gravity245@gmail.com",
    "crocodile5724@gmail.com",
    "fearless4@gmail.com",
    "road65warriror@gmail.com",
    "silentdeath464@gmail.com",
    "inflames99@gmail.com",
    "magician685@gmail.com",
    "day33a,day33a@gmail.com",
    "as3adandjoudi@gmail.com",
    "slangoand3fouf@gmail.com",
    "abonaderandhasan@gmail.com",
    "3adeltractor@gmail.com",
    "joudianddeeba@gmail.com",
    "m5tarandslango@gmail.com",
    "day33a.day33a.2006@gmail.com",
    "antawahadhywen@gmail.com",
    "ahmedanddubi@gmail.com",
    "aloahdydhgjdvid@gmail.com",
    "alosh2008909@gmail.com",
    "as3addied-_-@gmail.com",
    "joudi3rbaji@gmail.com",
    "mhmdlollollololol@gmail.com",
    "cuacluter2820909@gmail.com",
    "messigoutrinaldosuii@gmail.com",
    "programingvsodding@gmail.com",
    "aliisopsoajipdlnlisa@gmail.com",
    "momsd2728alidjdbdhmdn@gmail.com",
    "alihdkdbm7328932932@gmail.com",
    "903893dnjsnlS@gmail.com",
    "nsdjh783892032@gmail.com",
    "llllmmmmxxxxssswww@gmail.com",
    "909313787huh@gmail.com",
    "mommomdadadadkh872@gmail.com",
    "alisahekkkk789@gmail.com",
    "isrealislikemyass@gmail.com",
    "americaislikemyass@gmail.com",
    "#freeplastine@gmail.com",
    "inzumaeleven1223@gmail.com",
]
var passwords = [
    "loffy3mkya2hmbl",
    "nnetflixvsshahid",
    "posseyis90",
    "dogiscute32",
    "catisdogs23",
    "1+1=3poopo",
    "momkioksks23",
    "babaisbsis23",
    "9039289jnskn",
    "23hihoalsas",
    "32sdsadssasa",
    "neghiboris32",
    "upanddown2008",
    "isrealisshit2006",
    "salehandas2ad",
    "opopopjjdnj234",
   "poseydo5913",
   "miningpoll",
   "divagra3915",
   "hiltongargerr",
   "wonderfolss",
   "perebark226",
   "sniped@5mi",
   "diadblofix",
   "monauraesk",
   "az.premiumax",
   "Mail33@998",
   "#dsjojdhsou",
   "a79898*&*&*&",
   "popopopo90291",
   "99999999a",
   "5641324165",
   "@#Q!!@#*J@I&ON",
   "lolos762378&*&&)",
   "dark123321",
   "aliibrahinm2998",
   "allahw2kbr1@@",
   "allahwahad1@@",
   "@_@happyface",
   ":(sadface",
   "/ali/ali/ali20098",
   "098n345sc",
   "898948758@#@",
   "@#@saaaadsal",
   "demonslayer3mkyahywen",
   "onepiece3d4d5d=>3mk2",
   "attackontittan+>3mk3",
   "coffe+sugar=>nescafe-_-+_+lolk",
   "hookpoplollolnddddd",
   "snakeandcobraofsnakeissos",
   "poppoppoppop9006323",
   "momissocute3033",
   "dadhavevilla2023",
   "EvarALOL313414",
   "sleepisbad:(",
   "poorwaterisosbad",
   "dontputthispassword",
   "pokemon4ever",
   "iyot14398",
   "pubgisforniteiskok",
   "awawawawwawd27423",
   "34242087238023470234",
   "id->popshjdsd",
   "<->/-03hdhjd",
   "computerisposisb",
   "foodiasbadedxcf",
   "554533",
   "2mam2lmahdi303",
   "elizabethlove2255",
   "513you546pop900",
   "mommodsmmomdad",
   "wdsass@333333909",
   "momkokosuyugyia",
   "day33aday33alol",
   "mousemousees900",
   "joudiandas3ad90",
   "908374890327034l",
   "iohekjiyhdfo",
   "djlhdsjkldf",
   "ewewdffd",
   "dssdfsdfsdf",
   "3343332^&(!E^",
   "&^sssfdf",
   "jdkjasdoihs[o",
   "ss76283973ihids",
   "l,swdwefds",
   "l,dfsdfsfdsfd",
   "l,sdfffsdfsd",
   "pdkp[dfsdfds],",
   "ewqeqwew",
   "hjgjkolwq",
   "%^*&)(_+!@assa",
   "sassd909230",
   "saasasa23ew78",
   "8374982*&*&*)",
   "*&()*@(*losldh",
   "comdomphychrm32",
   "892comdomlol829",
   "8603908943HKHSA",
   "Amndkndd703789@@#",
]
// erores
var erore = console.error("passwords may be repeated ")
var erore = console.error("email may be repeated ")
// button
var button = document.getElementById("button");
var email = document.getElementById("email");
var password= document.getElementById("password")
// random pass & email
const RandomEmail = emails[Math.floor(Math.random() * emails.length)];
const Randompass = passwords[Math.floor(Math.random() * passwords.length)];



// generation of email and password
button.onclick = email_password;
function email_password(){
   email.innerHTML = `${RandomEmail}`
   password.innerHTML = `${Randompass}`
   button.onclick = ()=>{
      location.reload()
   }
}







